# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ratchet Plus
email: contact@kimsq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/rc" # the subpath of your site, e.g. /blog
url: "http://kimsq.github.io/" # the base hostname & protocol for your site
twitter_username: kimsqcom
github_username:  redblock

# Build settings
markdown: kramdown


# Navigation. If you do not like these modules, just remove them :D
navs:


  -
    href: /rc/getting-started
    label: Getting started

  -
    href: /rc//layout
    label: Layout

  -
    href: /rc//content
    label: Content

  -
    href: /rc//components
    label: Components

  -
    href: /rc//controls
    label: Controls

  -
    href: /rc//extensions
    label: Extensions